const http=require('http')
const express=require('express')
const morgan= require('morgan')
const bodyParser=require('body-parser')
const signUp=require('./signup')
const otpValidate=require('./validateOtp')
const cabDetails=require('./cabAndDrivers')
const userDetails=require("./userDetails")
const carBooking=require("./vehicleBooking")
const payment=require("./payment")
const loginOtpValidate=require('./login')
const app=express()

app.use(bodyParser.urlencoded({"extended":false}))
app.use(bodyParser.json())
app.use(morgan('combined'))
app.use("/authentication",signUp)
app.use("/vehicleAndDriver",cabDetails)
app.use("/home",carBooking)
app.use("/home",payment)
app.use("/login",loginOtpValidate)

http.createServer(app).listen(3000)